import { PUBLIC_WEB_FIXTURE_PATH_PREFIX } from '@geulbat/protocol/public-web-fixtures';
import {
  PUBLIC_GENERATED_REACT_BUNDLE_INLINE_PATH_PREFIX,
  type ReactBundleRuntimeManifest,
} from '@geulbat/protocol/react-bundle-inline-compile';

import { JS_RUNTIME_ROOT_ID } from '../js/document.js';
import { validateReactBundleEntryUrl } from '../../../artifacts/react-bundle/entry-url-policy.js';
import { REACT_ARTIFACT_RUNTIME_MODULE_SOURCES } from './runtime-module-sources.js';

export const REACT_BUNDLE_RUNTIME_ROOT_ID = 'geulbat-react-root';
export const REACT_BUNDLE_RUNTIME_ENTRY_ROOT_ID = 'root';
export const GEULBAT_REACT_RUNTIME_GLOBAL = '__GEULBAT_REACT_RUNTIME__';

export function buildReactBundleArtifactRuntimePayload(
  manifest: ReactBundleRuntimeManifest,
): string {
  const entryUrlValidation = validateReactBundleEntryUrl(manifest.entryUrl);
  if (!entryUrlValidation.ok) {
    throw new Error(entryUrlValidation.detail);
  }

  const escapedEntryUrl = JSON.stringify(entryUrlValidation.entryUrl).replace(
    /</g,
    '\\u003C',
  );
  const escapedModuleSources = JSON.stringify(
    REACT_ARTIFACT_RUNTIME_MODULE_SOURCES,
  ).replace(/</g, '\\u003C');

  return [
    '(async () => {',
    `const __geulbatReactRuntimeModuleSources__ = ${escapedModuleSources};`,
    'const __geulbatPolicyErrorName__ = "GeulbatPolicyBlockedError";',
    `const __geulbatRuntimeContainer__ = document.getElementById(${JSON.stringify(JS_RUNTIME_ROOT_ID)});`,
    "if (!__geulbatRuntimeContainer__) { throw new Error('react bundle runtime container is unavailable'); }",
    'const __geulbatRenderPolicyError__ = (detail) => {',
    '  __geulbatRuntimeContainer__.innerHTML = "";',
    '  const container = document.createElement("div");',
    '  container.className = "geulbat-js-runtime-error";',
    '  container.append(document.createTextNode("이 캔버스는 현재 웹쉘 경계를 넘는 동작 때문에 일부 기능을 실행하지 못했습니다."));',
    '  const detailNode = document.createElement("small");',
    '  detailNode.textContent = String(detail);',
    '  container.append(detailNode);',
    '  __geulbatRuntimeContainer__.append(container);',
    '};',
    'const __geulbatFailPolicy__ = (detail) => {',
    '  __geulbatRenderPolicyError__(detail);',
    '  const error = new Error(String(detail));',
    '  error.name = __geulbatPolicyErrorName__;',
    '  throw error;',
    '};',
    `let __geulbatReactRoot__ = document.getElementById(${JSON.stringify(REACT_BUNDLE_RUNTIME_ROOT_ID)});`,
    'if (!__geulbatReactRoot__) {',
    '  __geulbatRuntimeContainer__.innerHTML = "";',
    '  __geulbatReactRoot__ = document.createElement("div");',
    `  __geulbatReactRoot__.id = ${JSON.stringify(REACT_BUNDLE_RUNTIME_ROOT_ID)};`,
    '  __geulbatRuntimeContainer__.appendChild(__geulbatReactRoot__);',
    '}',
    `let __geulbatEntryRoot__ = document.getElementById(${JSON.stringify(REACT_BUNDLE_RUNTIME_ENTRY_ROOT_ID)});`,
    'if (!__geulbatEntryRoot__) {',
    '  __geulbatReactRoot__.innerHTML = "";',
    '  __geulbatEntryRoot__ = document.createElement("div");',
    `  __geulbatEntryRoot__.id = ${JSON.stringify(REACT_BUNDLE_RUNTIME_ENTRY_ROOT_ID)};`,
    '  __geulbatReactRoot__.appendChild(__geulbatEntryRoot__);',
    '}',
    'const __geulbatModuleCache__ = Object.create(null);',
    'const __geulbatModuleFactories__ = Object.create(null);',
    'const __geulbatCreateModuleFactory__ = (moduleId, sourceText) =>',
    '  new Function("require", "module", "exports", `${sourceText}\\n//# sourceURL=geulbat-react-runtime/${moduleId}`);',
    'for (const [moduleId, sourceText] of Object.entries(__geulbatReactRuntimeModuleSources__)) {',
    '  __geulbatModuleFactories__[moduleId] = __geulbatCreateModuleFactory__(moduleId, sourceText);',
    '}',
    'const __geulbatRequire__ = (moduleId) => {',
    '  const cachedModule = __geulbatModuleCache__[moduleId];',
    '  if (cachedModule) {',
    '    return cachedModule.exports;',
    '  }',
    '  const factory = __geulbatModuleFactories__[moduleId];',
    '  if (typeof factory !== "function") {',
    '    throw new Error(`unsupported react runtime module: ${moduleId}`);',
    '  }',
    '  const module = { exports: {} };',
    '  __geulbatModuleCache__[moduleId] = module;',
    '  factory(__geulbatRequire__, module, module.exports);',
    '  return module.exports;',
    '};',
    'const __geulbatReact__ = __geulbatRequire__("react");',
    'const __geulbatReactDom__ = __geulbatRequire__("react-dom");',
    'const __geulbatReactDomClient__ = __geulbatRequire__("react-dom/client");',
    'const __geulbatScheduler__ = __geulbatRequire__("scheduler");',
    `globalThis[${JSON.stringify(GEULBAT_REACT_RUNTIME_GLOBAL)}] = Object.freeze({`,
    '  React: __geulbatReact__,',
    '  ReactDOM: __geulbatReactDom__,',
    '  ReactDOMClient: __geulbatReactDomClient__,',
    '  Scheduler: __geulbatScheduler__,',
    '  createElement: __geulbatReact__.createElement,',
    '  createRoot: __geulbatReactDomClient__.createRoot,',
    '  version: typeof __geulbatReact__.version === "string" ? __geulbatReact__.version : null,',
    '});',
    'const __geulbatStorageReady__ = Promise.resolve(',
    '  window.__GEULBAT_RUNTIME_STORAGE_READY__,',
    ').catch(() => undefined);',
    'const __geulbatEntryUrl__ = (() => {',
    `  const parsedEntryUrl = new URL(${escapedEntryUrl});`,
    `  const __geulbatIsFixturePath__ = parsedEntryUrl.pathname.startsWith(${JSON.stringify(PUBLIC_WEB_FIXTURE_PATH_PREFIX)});`,
    `  const __geulbatIsGeneratedPath__ = parsedEntryUrl.pathname.startsWith(${JSON.stringify(PUBLIC_GENERATED_REACT_BUNDLE_INLINE_PATH_PREFIX)});`,
    '  if (parsedEntryUrl.origin === window.location.origin && !__geulbatIsFixturePath__ && !__geulbatIsGeneratedPath__) {',
    '    __geulbatFailPolicy__("react bundle manifest entryUrl points at the current shell origin outside the public fixture/generated host");',
    '  }',
    '  return parsedEntryUrl.toString();',
    '})();',
    'const __geulbatBundleModule__ = await import(__geulbatEntryUrl__);',
    'const __geulbatBundleRegistration__ =',
    '  __geulbatBundleModule__ && typeof __geulbatBundleModule__ === "object"',
    '    ? __geulbatBundleModule__.default',
    '    : undefined;',
    'if (!__geulbatBundleRegistration__ || typeof __geulbatBundleRegistration__ !== "object") {',
    "  throw new Error('react bundle entry module must default export a bundle object');",
    '}',
    'if (typeof __geulbatBundleRegistration__.mount !== "function") {',
    "  throw new Error('react bundle entry module must default export a callable mount(args)');",
    '}',
    'const __geulbatCleanup__ = await Promise.resolve(__geulbatBundleRegistration__.mount({',
    '  root: __geulbatEntryRoot__,',
    `  runtime: globalThis[${JSON.stringify(GEULBAT_REACT_RUNTIME_GLOBAL)}],`,
    '  storage: window.storage,',
    '  storageReady: __geulbatStorageReady__,',
    '}));',
    'let __geulbatDidUnmount__ = false;',
    'const __geulbatSafeUnmount__ = () => {',
    '  if (__geulbatDidUnmount__) {',
    '    return;',
    '  }',
    '  __geulbatDidUnmount__ = true;',
    '  try {',
    '    if (typeof __geulbatCleanup__ === "function") {',
    '      __geulbatCleanup__();',
    '      return;',
    '    }',
    '    if (typeof __geulbatBundleRegistration__.unmount === "function") {',
    '      __geulbatBundleRegistration__.unmount(__geulbatEntryRoot__);',
    '    }',
    '  } catch (error) {',
    "    console.error('geulbat react bundle cleanup failed', error);",
    '  }',
    '};',
    'window.addEventListener("pagehide", __geulbatSafeUnmount__, { once: true });',
    'window.addEventListener("beforeunload", __geulbatSafeUnmount__, { once: true });',
    '})();',
    '',
  ].join('\n');
}
