// Generated from artifact-runtime-persistence-bootstrap-entry.ts by scripts/sync-artifact-runtime-sources.mjs.
// Do not edit this file by hand.
export const ARTIFACT_RUNTIME_PERSISTENCE_BOOTSTRAP_SOURCE = `(() => {
  // src/lib/json.ts
  function isRecord(value) {
    return !!value && typeof value === "object" && !Array.isArray(value);
  }
  function isPlainRecord(value) {
    if (!isRecord(value)) {
      return false;
    }
    const prototype = Reflect.getPrototypeOf(value);
    return prototype === Object.prototype || prototype === null;
  }
  function isString(value) {
    return typeof value === "string";
  }
  function isNumber(value) {
    return typeof value === "number" && Number.isFinite(value);
  }
  function tryParseJson(text) {
    try {
      return { ok: true, value: JSON.parse(text) };
    } catch {
      return { ok: false };
    }
  }
  function tryParseJsonWithGuard(text, guard) {
    const parsed = tryParseJson(text);
    if (!parsed.ok || !guard(parsed.value)) {
      return { ok: false };
    }
    return { ok: true, value: parsed.value };
  }
  function tryDecodeJson(text, decode) {
    const parsed = tryParseJson(text);
    if (!parsed.ok) {
      return { ok: false };
    }
    try {
      return { ok: true, value: decode(parsed.value) };
    } catch {
      return { ok: false };
    }
  }
  function tryParseJsonRecord(text) {
    return tryParseJsonWithGuard(text, isRecord);
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-bootstrap-types.ts
  function isPersistenceBootstrapSuccessResponseMessage(response) {
    if (!isRecord(response)) {
      return false;
    }
    const record = response;
    return record.ok === true && typeof record.kind === "string" && (typeof record.version === "string" || typeof record.version === "number") && typeof record.requestId === "string" && typeof record.scopeHandle === "string" && typeof record.verb === "string" && (record.revision === void 0 || record.revision === null || typeof record.revision === "string");
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-bootstrap-bridge.ts
  function createPersistenceResponseRouter({
    window: window2,
    verbs,
    store,
    pendingPersistenceRequests,
    clearPendingPersistenceRequest
  }) {
    return (event) => {
      if (event.source !== window2.parent || event.origin !== window2.__GEULBAT_PERSISTENCE_PARENT_ORIGIN__) {
        return;
      }
      const message = event.data;
      if (!store.isPlainRecord(message)) {
        return;
      }
      const response = message;
      if (response.kind !== window2.__GEULBAT_PERSISTENCE_RESPONSE_KIND__ || response.version !== window2.__GEULBAT_PERSISTENCE_BRIDGE_VERSION__ || typeof response.requestId !== "string" || response.scopeHandle !== window2.__GEULBAT_PERSISTENCE_SCOPE_HANDLE__ || response.verb !== verbs.loadVerb && response.verb !== verbs.saveVerb && response.verb !== verbs.clearVerb) {
        return;
      }
      const pending = pendingPersistenceRequests.get(response.requestId);
      if (!pending || pending.verb !== response.verb) {
        return;
      }
      clearPendingPersistenceRequest(response.requestId);
      if (response.ok) {
        if (!isPersistenceBootstrapSuccessResponseMessage(response)) {
          pending.reject(
            store.createPersistenceError(
              "persistence_unavailable",
              "runtime persistence response was malformed"
            )
          );
          return;
        }
        pending.resolve(response);
        return;
      }
      pending.reject(
        store.createPersistenceError(
          typeof response.errorCode === "string" ? response.errorCode : "persistence_unavailable",
          typeof response.message === "string" && response.message ? response.message : "runtime persistence request failed"
        )
      );
    };
  }
  function createArtifactRuntimePersistenceBridge(window2, verbs, store) {
    const DEFAULT_PERSISTENCE_REQUEST_TIMEOUT_MS = 5e3;
    const pendingPersistenceRequests = /* @__PURE__ */ new Map();
    let persistenceRequestIndex = 0;
    const requestTimeoutMs = typeof window2.__GEULBAT_PERSISTENCE_REQUEST_TIMEOUT_MS__ === "number" && Number.isFinite(window2.__GEULBAT_PERSISTENCE_REQUEST_TIMEOUT_MS__) && window2.__GEULBAT_PERSISTENCE_REQUEST_TIMEOUT_MS__ > 0 ? window2.__GEULBAT_PERSISTENCE_REQUEST_TIMEOUT_MS__ : DEFAULT_PERSISTENCE_REQUEST_TIMEOUT_MS;
    const scheduleTimeout = typeof window2.setTimeout === "function" ? window2.setTimeout.bind(window2) : globalThis.setTimeout.bind(globalThis);
    const cancelTimeout = typeof window2.clearTimeout === "function" ? window2.clearTimeout.bind(window2) : globalThis.clearTimeout.bind(globalThis);
    const createRequestId = () => {
      persistenceRequestIndex += 1;
      return "persistence-" + Date.now().toString(16) + "-" + persistenceRequestIndex.toString(16);
    };
    const clearPendingPersistenceRequest = (requestId) => {
      const pending = pendingPersistenceRequests.get(requestId);
      if (!pending) {
        return null;
      }
      pendingPersistenceRequests.delete(requestId);
      cancelTimeout(pending.timeoutHandle);
      return pending;
    };
    const postPersistenceRequest = (verb, extras = {}) => new Promise(
      (resolve, reject) => {
        const parent = window2.parent;
        if (!parent || parent === window2 || !("postMessage" in parent)) {
          reject(
            store.createPersistenceError(
              "persistence_unavailable",
              "runtime persistence parent bridge is unavailable"
            )
          );
          return;
        }
        const requestId = createRequestId();
        const timeoutHandle = scheduleTimeout(() => {
          const pending = clearPendingPersistenceRequest(requestId);
          if (!pending) {
            return;
          }
          pending.reject(
            store.createPersistenceError(
              "persistence_unavailable",
              "runtime persistence request timed out"
            )
          );
        }, requestTimeoutMs);
        pendingPersistenceRequests.set(requestId, {
          resolve,
          reject,
          verb,
          timeoutHandle
        });
        try {
          parent.postMessage(
            {
              kind: window2.__GEULBAT_PERSISTENCE_REQUEST_KIND__,
              version: window2.__GEULBAT_PERSISTENCE_BRIDGE_VERSION__,
              requestId,
              scopeHandle: window2.__GEULBAT_PERSISTENCE_SCOPE_HANDLE__,
              verb,
              ...extras
            },
            window2.__GEULBAT_PERSISTENCE_PARENT_ORIGIN__
          );
        } catch (error) {
          const pending = clearPendingPersistenceRequest(requestId);
          pending?.reject(
            store.createPersistenceError(
              "persistence_unavailable",
              error instanceof Error && error.message ? \`runtime persistence request failed before dispatch: \${error.message}\` : "runtime persistence request failed before dispatch"
            )
          );
        }
      }
    );
    window2.addEventListener(
      "message",
      createPersistenceResponseRouter({
        window: window2,
        verbs,
        store,
        pendingPersistenceRequests,
        clearPendingPersistenceRequest
      })
    );
    const rawPersistenceApi = Object.freeze({
      loadState() {
        return postPersistenceRequest(verbs.loadVerb);
      },
      saveState(state, expectedRevision) {
        return postPersistenceRequest(verbs.saveVerb, {
          state,
          expectedRevision
        });
      },
      clearState(expectedRevision) {
        return postPersistenceRequest(verbs.clearVerb, {
          expectedRevision
        });
      }
    });
    const persistenceApi = Object.freeze({
      loadState() {
        try {
          store.assertSharedStorageAvailable();
        } catch (error) {
          return Promise.reject(store.stabilizePersistenceError(error));
        }
        return rawPersistenceApi.loadState();
      },
      saveState(state, expectedRevision) {
        try {
          store.assertSharedStorageAvailable();
        } catch (error) {
          return Promise.reject(store.stabilizePersistenceError(error));
        }
        return rawPersistenceApi.saveState(state, expectedRevision);
      },
      clearState(expectedRevision) {
        try {
          store.assertSharedStorageAvailable();
        } catch (error) {
          return Promise.reject(store.stabilizePersistenceError(error));
        }
        return rawPersistenceApi.clearState(expectedRevision);
      }
    });
    return {
      rawPersistenceApi,
      persistenceApi
    };
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-authority-state.ts
  var STORAGE_NAMESPACE_KEY = "__geulbat_storage_namespace_v1__";
  var DATABASE_NAMESPACE_KEY = "__geulbat_db_namespace_v1__";
  function createArtifactRuntimePersistenceAuthorityState() {
    const createNullPrototypeMap = () => {
      const next = {};
      Object.setPrototypeOf(next, null);
      return next;
    };
    const cloneToNullPrototypeMap = (record) => {
      const next = createNullPrototypeMap();
      for (const [key, value] of Object.entries(record)) {
        next[key] = value;
      }
      return next;
    };
    let currentStorageMap = createNullPrototypeMap();
    let currentSessionStorageMap = createNullPrototypeMap();
    let currentDatabaseMap = createNullPrototypeMap();
    let committedStorageMap = createNullPrototypeMap();
    let committedDatabaseMap = createNullPrototypeMap();
    let currentStorageRevision = null;
    const toPersistedStorageState = (record) => {
      const next = {};
      for (const key of Object.keys(record)) {
        next[key] = record[key];
      }
      return next;
    };
    const cloneJsonValue = (value) => {
      if (Array.isArray(value)) {
        return value.map((entry) => cloneJsonValue(entry));
      }
      if (!isRecord(value)) {
        return value;
      }
      const next = {};
      for (const key of Object.keys(value)) {
        next[key] = cloneJsonValue(value[key]);
      }
      return next;
    };
    const listStorageKeys = () => Object.keys(currentStorageMap).sort(
      (left, right) => left.localeCompare(right)
    );
    const listSessionStorageKeys = () => Object.keys(currentSessionStorageMap).sort(
      (left, right) => left.localeCompare(right)
    );
    const listDatabaseKeys = () => Object.keys(currentDatabaseMap).sort(
      (left, right) => left.localeCompare(right)
    );
    const buildPersistedAuthorityState = (storageRecord, databaseRecord) => {
      const hasStorageEntries = Object.keys(storageRecord).length > 0;
      const hasDatabaseEntries = Object.keys(databaseRecord).length > 0;
      if (!hasStorageEntries && !hasDatabaseEntries) {
        return null;
      }
      if (!hasDatabaseEntries) {
        return toPersistedStorageState(storageRecord);
      }
      const next = {
        [DATABASE_NAMESPACE_KEY]: toPersistedStorageState(databaseRecord)
      };
      if (hasStorageEntries) {
        next[STORAGE_NAMESPACE_KEY] = toPersistedStorageState(storageRecord);
      }
      return next;
    };
    const buildStateWithMutations = (storageBase, databaseBase, mutations) => {
      const next = {
        storageMap: cloneToNullPrototypeMap(storageBase),
        databaseMap: cloneToNullPrototypeMap(databaseBase)
      };
      for (const mutation of mutations) {
        mutation.apply(next);
      }
      return next;
    };
    const refreshCurrentAuthorityState = (mutations) => {
      const next = buildStateWithMutations(
        committedStorageMap,
        committedDatabaseMap,
        mutations
      );
      currentStorageMap = next.storageMap;
      currentDatabaseMap = next.databaseMap;
    };
    const buildStateThroughMutation = (mutations, mutationId) => {
      const targetIndex = mutations.findIndex(
        (mutation) => mutation.id === mutationId
      );
      if (targetIndex < 0) {
        return null;
      }
      return buildStateWithMutations(
        committedStorageMap,
        committedDatabaseMap,
        mutations.slice(0, targetIndex + 1)
      );
    };
    const createNextSessionStorageMap = (mutate) => {
      const next = cloneToNullPrototypeMap(currentSessionStorageMap);
      mutate(next);
      currentSessionStorageMap = next;
      return cloneToNullPrototypeMap(next);
    };
    const replaceCommittedAuthorityState = (next) => {
      committedStorageMap = cloneToNullPrototypeMap(next.storageMap);
      committedDatabaseMap = cloneToNullPrototypeMap(next.databaseMap);
      currentStorageRevision = next.revision;
      refreshCurrentAuthorityState([]);
    };
    return {
      STORAGE_NAMESPACE_KEY,
      DATABASE_NAMESPACE_KEY,
      cloneToNullPrototypeMap,
      cloneJsonValue,
      listStorageKeys,
      listSessionStorageKeys,
      listDatabaseKeys,
      buildPersistedAuthorityState,
      refreshCurrentAuthorityState,
      buildStateThroughMutation,
      createNextSessionStorageMap,
      replaceCommittedAuthorityState,
      readCurrentStorageMap: () => currentStorageMap,
      readCurrentSessionStorageMap: () => currentSessionStorageMap,
      readCurrentDatabaseMap: () => currentDatabaseMap,
      readCurrentStorageRevision: () => currentStorageRevision
    };
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-authority-io.ts
  function createArtifactRuntimePersistenceAuthorityIo(args) {
    const { authorityState, validation } = args;
    const hasOwn = (value, key) => Object.hasOwn(value, key);
    const loadCurrentAuthorityState = async (rawPersistenceApi) => {
      const result = await rawPersistenceApi.loadState();
      if (result.state === null) {
        return {
          storageMap: authorityState.cloneToNullPrototypeMap({}),
          databaseMap: authorityState.cloneToNullPrototypeMap({}),
          revision: result.revision ?? null
        };
      }
      if (!validation.isPlainRecord(result.state)) {
        throw validation.createPersistenceError(
          "persistence_blocked",
          "runtime storage scope is not a valid authority record"
        );
      }
      if (!hasOwn(result.state, STORAGE_NAMESPACE_KEY) && !hasOwn(result.state, DATABASE_NAMESPACE_KEY)) {
        return {
          storageMap: authorityState.cloneToNullPrototypeMap(result.state),
          databaseMap: authorityState.cloneToNullPrototypeMap({}),
          revision: result.revision ?? null
        };
      }
      const storageState = hasOwn(result.state, STORAGE_NAMESPACE_KEY) ? result.state[STORAGE_NAMESPACE_KEY] : {};
      const databaseState = hasOwn(result.state, DATABASE_NAMESPACE_KEY) ? result.state[DATABASE_NAMESPACE_KEY] : {};
      if (!validation.isPlainRecord(storageState) || !validation.isPlainRecord(databaseState)) {
        throw validation.createPersistenceError(
          "persistence_blocked",
          "runtime storage scope is not a valid authority record"
        );
      }
      for (const key of Object.keys(databaseState)) {
        const normalizedDatabaseKey = validation.normalizeDatabaseKey(key);
        validation.assertDatabaseValue(databaseState[normalizedDatabaseKey]);
      }
      return {
        storageMap: authorityState.cloneToNullPrototypeMap(storageState),
        databaseMap: authorityState.cloneToNullPrototypeMap(databaseState),
        revision: result.revision ?? null
      };
    };
    const persistCurrentAuthorityState = async (rawPersistenceApi, storageRecord, databaseRecord, revision) => {
      const persistedState = authorityState.buildPersistedAuthorityState(
        storageRecord,
        databaseRecord
      );
      if (persistedState === null) {
        return rawPersistenceApi.clearState(revision);
      }
      return rawPersistenceApi.saveState(persistedState, revision);
    };
    const ensureStorageReady = async (window2) => {
      const ready = window2.__GEULBAT_RUNTIME_STORAGE_READY__;
      if (!ready) {
        throw validation.createPersistenceError(
          "persistence_unavailable",
          "runtime storage bootstrap is not ready"
        );
      }
      await ready;
    };
    return {
      loadCurrentAuthorityState,
      persistCurrentAuthorityState,
      ensureStorageReady
    };
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-mutation-queue.ts
  var STORAGE_RETRY_LIMIT = 3;
  function createArtifactRuntimePersistenceMutationQueue({
    authorityState,
    createPersistenceError,
    stabilizePersistenceError,
    isPersistenceConflict,
    assertSharedStorageAvailable,
    loadCurrentAuthorityState,
    persistCurrentAuthorityState,
    markStorageUnavailable
  }) {
    let storageWriteQueue = Promise.resolve();
    let pendingMutationIndex = 0;
    const pendingMutations = [];
    const waitForCommittedStorageWrites = () => storageWriteQueue.then(
      () => void 0,
      () => void 0
    );
    const enqueueStorageWrite = (operation) => {
      const result = storageWriteQueue.then(operation, operation);
      storageWriteQueue = result.then(
        () => void 0,
        () => void 0
      );
      return result;
    };
    const removePendingMutation = (mutationId) => {
      const targetIndex = pendingMutations.findIndex(
        (mutation) => mutation.id === mutationId
      );
      if (targetIndex >= 0) {
        pendingMutations.splice(targetIndex, 1);
      }
    };
    const schedulePersistedMutation = (rawPersistenceApi, applyMutation) => {
      pendingMutationIndex += 1;
      const pendingMutation = {
        id: pendingMutationIndex,
        apply: applyMutation
      };
      pendingMutations.push(pendingMutation);
      authorityState.refreshCurrentAuthorityState(pendingMutations);
      return enqueueStorageWrite(async () => {
        assertSharedStorageAvailable();
        let remaining = STORAGE_RETRY_LIMIT;
        while (remaining-- > 0) {
          const next = authorityState.buildStateThroughMutation(
            pendingMutations,
            pendingMutation.id
          );
          if (!next) {
            return;
          }
          const persistResult = await persistCurrentAuthorityState(
            rawPersistenceApi,
            next.storageMap,
            next.databaseMap,
            authorityState.readCurrentStorageRevision()
          ).then(
            (result) => ({ ok: true, result }),
            (error) => ({ ok: false, error })
          );
          if (persistResult.ok) {
            authorityState.replaceCommittedAuthorityState({
              storageMap: next.storageMap,
              databaseMap: next.databaseMap,
              revision: persistResult.result.revision ?? null
            });
            removePendingMutation(pendingMutation.id);
            authorityState.refreshCurrentAuthorityState(pendingMutations);
            return;
          }
          if (isPersistenceConflict(persistResult.error) && remaining > 0) {
            authorityState.replaceCommittedAuthorityState(
              await loadCurrentAuthorityState(rawPersistenceApi)
            );
            authorityState.refreshCurrentAuthorityState(pendingMutations);
            continue;
          }
          if (isPersistenceConflict(persistResult.error)) {
            break;
          }
          throw stabilizePersistenceError(persistResult.error);
        }
        throw createPersistenceError(
          "persistence_unavailable",
          "runtime storage is unavailable"
        );
      }).catch((error) => {
        throw markStorageUnavailable(error);
      });
    };
    return {
      waitForCommittedStorageWrites,
      schedulePersistedMutation
    };
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-validation.ts
  function createArtifactRuntimePersistenceValidation() {
    const storageReservedKeys = /* @__PURE__ */ new Set([
      "__proto__",
      "constructor",
      "prototype",
      STORAGE_NAMESPACE_KEY,
      DATABASE_NAMESPACE_KEY
    ]);
    const createPersistenceError = (code, message) => Object.assign(new Error(message), {
      name: "GeulbatRuntimePersistenceError",
      code
    });
    const clonePersistenceError = (error) => createPersistenceError(error.code, error.message);
    const stabilizePersistenceError = (error, fallbackCode = "persistence_unavailable", fallbackMessage = "runtime persistence unavailable") => {
      const code = error && typeof error === "object" && "code" in error && typeof error.code === "string" ? error.code : fallbackCode;
      const message = error instanceof Error && error.message ? error.message : error && typeof error === "object" && "message" in error && typeof error.message === "string" && error.message ? error.message : fallbackMessage;
      if (code === "persistence_blocked" || code === "persistence_quota_exceeded" || code === "persistence_unavailable") {
        return createPersistenceError(code, message);
      }
      return createPersistenceError(fallbackCode, message);
    };
    const isPersistenceConflict = (error) => !!error && typeof error === "object" && "code" in error && error.code === "persistence_conflict";
    const isPlainRecord2 = (value) => {
      if (!value || typeof value !== "object" || Array.isArray(value)) {
        return false;
      }
      const prototype = Object.getPrototypeOf(value);
      if (prototype === null || prototype === Object.prototype) {
        return true;
      }
      return Object.prototype.toString.call(value) === "[object Object]" && typeof prototype === "object" && "constructor" in prototype && typeof prototype.constructor === "function" && prototype.constructor.name === "Object";
    };
    const isJsonStorageValue = (value, seen = /* @__PURE__ */ new Set()) => {
      if (value === null) {
        return true;
      }
      switch (typeof value) {
        case "string":
        case "boolean":
          return true;
        case "number":
          return Number.isFinite(value);
        case "object":
          break;
        default:
          return false;
      }
      if (seen.has(value)) {
        return false;
      }
      seen.add(value);
      try {
        if (Array.isArray(value)) {
          return value.every((entry) => isJsonStorageValue(entry, seen));
        }
        if (!isPlainRecord2(value)) {
          return false;
        }
        return Object.keys(value).every(
          (key) => isJsonStorageValue(value[key], seen)
        );
      } finally {
        seen.delete(value);
      }
    };
    function assertStorageKey(key) {
      if (typeof key !== "string" || key.length === 0) {
        throw createPersistenceError(
          "persistence_blocked",
          "storage key must be a non-empty string"
        );
      }
      if (storageReservedKeys.has(key)) {
        throw createPersistenceError(
          "persistence_blocked",
          "storage key is reserved in artifact runtime storage"
        );
      }
    }
    const assertStorageValue = (value) => {
      if (value === null || !isJsonStorageValue(value)) {
        throw createPersistenceError(
          "persistence_blocked",
          "storage value must be JSON-serializable and not top-level null"
        );
      }
    };
    function assertDatabaseKey(key) {
      if (typeof key !== "string" || key.length === 0) {
        throw createPersistenceError(
          "persistence_blocked",
          "database key must be a non-empty string"
        );
      }
      if (storageReservedKeys.has(key)) {
        throw createPersistenceError(
          "persistence_blocked",
          "database key is reserved in artifact runtime storage"
        );
      }
    }
    const assertDatabaseValue = (value) => {
      if (value === null || !isJsonStorageValue(value)) {
        throw createPersistenceError(
          "persistence_blocked",
          "database value must be JSON-serializable and not top-level null"
        );
      }
    };
    const normalizeStorageKey = (key) => {
      const normalized = String(key);
      assertStorageKey(normalized);
      return normalized;
    };
    const normalizeDatabaseKey = (key) => {
      const normalized = String(key);
      assertDatabaseKey(normalized);
      return normalized;
    };
    const normalizeStorageIndex = (index) => {
      const normalized = Number(index);
      if (!Number.isInteger(normalized) || normalized < 0) {
        return null;
      }
      return normalized;
    };
    return {
      createPersistenceError,
      clonePersistenceError,
      stabilizePersistenceError,
      isPersistenceConflict,
      isPlainRecord: isPlainRecord2,
      assertStorageKey,
      assertStorageValue,
      assertDatabaseKey,
      assertDatabaseValue,
      normalizeStorageKey,
      normalizeDatabaseKey,
      normalizeStorageIndex
    };
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-browser-storage-facades.ts
  function createLocalStorageFacade({
    bridge,
    store,
    clearRecord,
    markDeferredPersistenceFailure
  }) {
    return Object.freeze({
      getItem(key) {
        store.assertStorageBootstrapReady();
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeStorageKey(key);
        const currentStorageMap = store.readCurrentStorageMap();
        return Object.hasOwn(currentStorageMap, normalizedKey) ? String(currentStorageMap[normalizedKey]) : null;
      },
      setItem(key, value) {
        store.assertStorageBootstrapReady();
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeStorageKey(key);
        void store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ storageMap }) => {
            storageMap[normalizedKey] = String(value);
          }
        ).catch(markDeferredPersistenceFailure);
      },
      removeItem(key) {
        store.assertStorageBootstrapReady();
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeStorageKey(key);
        const currentStorageMap = store.readCurrentStorageMap();
        if (!Object.hasOwn(currentStorageMap, normalizedKey)) {
          return;
        }
        void store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ storageMap }) => {
            delete storageMap[normalizedKey];
          }
        ).catch(markDeferredPersistenceFailure);
      },
      clear() {
        store.assertStorageBootstrapReady();
        store.assertSharedStorageAvailable();
        if (Object.keys(store.readCurrentStorageMap()).length === 0) {
          return;
        }
        void store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ storageMap }) => {
            clearRecord(storageMap);
          }
        ).catch(markDeferredPersistenceFailure);
      },
      key(index) {
        store.assertStorageBootstrapReady();
        store.assertSharedStorageAvailable();
        const normalizedIndex = store.normalizeStorageIndex(index);
        if (normalizedIndex === null) {
          return null;
        }
        return store.listStorageKeys()[normalizedIndex] ?? null;
      },
      get length() {
        store.assertStorageBootstrapReady();
        store.assertSharedStorageAvailable();
        return store.listStorageKeys().length;
      }
    });
  }
  function createSessionStorageFacade({
    store,
    clearRecord
  }) {
    return Object.freeze({
      getItem(key) {
        store.assertStorageBootstrapReady();
        const normalizedKey = store.normalizeStorageKey(key);
        const currentSessionStorageMap = store.readCurrentSessionStorageMap();
        return Object.hasOwn(currentSessionStorageMap, normalizedKey) ? String(currentSessionStorageMap[normalizedKey]) : null;
      },
      setItem(key, value) {
        store.assertStorageBootstrapReady();
        const normalizedKey = store.normalizeStorageKey(key);
        store.createNextSessionStorageMap((map) => {
          map[normalizedKey] = String(value);
        });
      },
      removeItem(key) {
        store.assertStorageBootstrapReady();
        const normalizedKey = store.normalizeStorageKey(key);
        const currentSessionStorageMap = store.readCurrentSessionStorageMap();
        if (!Object.hasOwn(currentSessionStorageMap, normalizedKey)) {
          return;
        }
        store.createNextSessionStorageMap((map) => {
          delete map[normalizedKey];
        });
      },
      clear() {
        store.assertStorageBootstrapReady();
        if (Object.keys(store.readCurrentSessionStorageMap()).length === 0) {
          return;
        }
        store.createNextSessionStorageMap(clearRecord);
      },
      key(index) {
        store.assertStorageBootstrapReady();
        const normalizedIndex = store.normalizeStorageIndex(index);
        if (normalizedIndex === null) {
          return null;
        }
        return store.listSessionStorageKeys()[normalizedIndex] ?? null;
      },
      get length() {
        store.assertStorageBootstrapReady();
        return store.listSessionStorageKeys().length;
      }
    });
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-storage-facades.ts
  function createLogicalDatabaseFacade({
    window: window2,
    bridge,
    store,
    clearRecord
  }) {
    return Object.freeze({
      async get(key) {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeDatabaseKey(key);
        await store.waitForCommittedStorageWrites();
        store.assertSharedStorageAvailable();
        const currentDatabaseMap = store.readCurrentDatabaseMap();
        return Object.hasOwn(currentDatabaseMap, normalizedKey) ? store.cloneJsonValue(currentDatabaseMap[normalizedKey]) : null;
      },
      async put(key, value) {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeDatabaseKey(key);
        store.assertDatabaseValue(value);
        return store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ databaseMap }) => {
            databaseMap[normalizedKey] = store.cloneJsonValue(value);
          }
        );
      },
      async delete(key) {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeDatabaseKey(key);
        const currentDatabaseMap = store.readCurrentDatabaseMap();
        if (!Object.hasOwn(currentDatabaseMap, normalizedKey)) {
          return false;
        }
        await store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ databaseMap }) => {
            delete databaseMap[normalizedKey];
          }
        );
        return true;
      },
      async keys() {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        await store.waitForCommittedStorageWrites();
        store.assertSharedStorageAvailable();
        return store.listDatabaseKeys();
      },
      async clear() {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        if (Object.keys(store.readCurrentDatabaseMap()).length === 0) {
          return;
        }
        await store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ databaseMap }) => {
            clearRecord(databaseMap);
          }
        );
      }
    });
  }
  function createStorageFacade({
    window: window2,
    bridge,
    store
  }) {
    return Object.freeze({
      async get(key) {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeStorageKey(key);
        await store.waitForCommittedStorageWrites();
        store.assertSharedStorageAvailable();
        const currentStorageMap = store.readCurrentStorageMap();
        return Object.hasOwn(currentStorageMap, normalizedKey) ? currentStorageMap[normalizedKey] : null;
      },
      async set(key, value) {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeStorageKey(key);
        store.assertStorageValue(value);
        return store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ storageMap }) => {
            storageMap[normalizedKey] = value;
          }
        );
      },
      async delete(key) {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        const normalizedKey = store.normalizeStorageKey(key);
        const currentStorageMap = store.readCurrentStorageMap();
        if (!Object.hasOwn(currentStorageMap, normalizedKey)) {
          return false;
        }
        await store.schedulePersistedMutation(
          bridge.rawPersistenceApi,
          ({ storageMap }) => {
            delete storageMap[normalizedKey];
          }
        );
        return true;
      },
      async list(prefix) {
        await store.ensureStorageReady(window2);
        store.assertSharedStorageAvailable();
        if (prefix !== void 0 && typeof prefix !== "string") {
          throw store.createPersistenceError(
            "persistence_blocked",
            "storage prefix must be a string when provided"
          );
        }
        await store.waitForCommittedStorageWrites();
        store.assertSharedStorageAvailable();
        return store.listStorageKeys().filter(
          (key) => prefix === void 0 ? true : key.startsWith(prefix)
        );
      }
    });
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-bootstrap-runtime.ts
  function createArtifactRuntimePersistenceStore() {
    const authorityState = createArtifactRuntimePersistenceAuthorityState();
    const validation = createArtifactRuntimePersistenceValidation();
    let storageBootstrapReady = false;
    let sharedStorageAuthorityError = null;
    const authorityIo = createArtifactRuntimePersistenceAuthorityIo({
      authorityState,
      validation
    });
    const getSharedStorageAuthorityError = () => sharedStorageAuthorityError ? validation.clonePersistenceError(sharedStorageAuthorityError) : null;
    const markStorageUnavailable = (error) => {
      const stabilized = validation.stabilizePersistenceError(
        error,
        "persistence_unavailable",
        "runtime storage is unavailable"
      );
      if (!sharedStorageAuthorityError) {
        sharedStorageAuthorityError = stabilized;
        const scopeUnavailableByDesign = stabilized.message.includes(
          "scope is unavailable for this artifact"
        );
        if (!scopeUnavailableByDesign && typeof console !== "undefined" && console && typeof console.error === "function") {
          console.error("[geulbat] runtime storage degraded", stabilized);
        }
      }
      return getSharedStorageAuthorityError() ?? validation.createPersistenceError(
        "persistence_unavailable",
        "runtime storage is unavailable"
      );
    };
    const assertStorageBootstrapReady = () => {
      if (storageBootstrapReady) {
        return;
      }
      throw validation.createPersistenceError(
        "persistence_unavailable",
        "runtime storage bootstrap is not ready"
      );
    };
    const assertSharedStorageAvailable = () => {
      const degraded = getSharedStorageAuthorityError();
      if (degraded) {
        throw degraded;
      }
    };
    const mutationQueue = createArtifactRuntimePersistenceMutationQueue({
      authorityState,
      createPersistenceError: validation.createPersistenceError,
      stabilizePersistenceError: validation.stabilizePersistenceError,
      isPersistenceConflict: validation.isPersistenceConflict,
      assertSharedStorageAvailable,
      loadCurrentAuthorityState: authorityIo.loadCurrentAuthorityState,
      persistCurrentAuthorityState: authorityIo.persistCurrentAuthorityState,
      markStorageUnavailable
    });
    return {
      bridgeStore: {
        createPersistenceError: validation.createPersistenceError,
        stabilizePersistenceError: validation.stabilizePersistenceError,
        assertSharedStorageAvailable,
        isPlainRecord: validation.isPlainRecord
      },
      bootstrapLifecycle: {
        markStorageUnavailable,
        loadCurrentAuthorityState: authorityIo.loadCurrentAuthorityState,
        replaceCurrentAuthorityState: authorityState.replaceCommittedAuthorityState,
        setStorageBootstrapReady(next) {
          storageBootstrapReady = next;
        }
      },
      storageFacadeStore: {
        createPersistenceError: validation.createPersistenceError,
        assertStorageBootstrapReady,
        assertSharedStorageAvailable,
        ensureStorageReady: authorityIo.ensureStorageReady,
        cloneJsonValue: authorityState.cloneJsonValue,
        listStorageKeys: authorityState.listStorageKeys,
        listSessionStorageKeys: authorityState.listSessionStorageKeys,
        listDatabaseKeys: authorityState.listDatabaseKeys,
        assertStorageKey: validation.assertStorageKey,
        assertStorageValue: validation.assertStorageValue,
        assertDatabaseKey: validation.assertDatabaseKey,
        assertDatabaseValue: validation.assertDatabaseValue,
        waitForCommittedStorageWrites: mutationQueue.waitForCommittedStorageWrites,
        normalizeStorageKey: validation.normalizeStorageKey,
        normalizeDatabaseKey: validation.normalizeDatabaseKey,
        normalizeStorageIndex: validation.normalizeStorageIndex,
        schedulePersistedMutation: mutationQueue.schedulePersistedMutation,
        createNextSessionStorageMap: authorityState.createNextSessionStorageMap,
        readCurrentStorageMap: authorityState.readCurrentStorageMap,
        readCurrentSessionStorageMap: authorityState.readCurrentSessionStorageMap,
        readCurrentDatabaseMap: authorityState.readCurrentDatabaseMap
      }
    };
  }
  function installPersistenceFacadeProperty(window2, property, value, handleAssignmentFailure) {
    try {
      Object.defineProperty(window2, property, {
        configurable: true,
        get() {
          return value;
        }
      });
      return;
    } catch (error) {
      reportPersistenceFacadeDescriptorInstallFailure(property, error);
    }
    try {
      window2[property] = value;
    } catch (error) {
      handleAssignmentFailure(error);
    }
  }
  function reportPersistenceFacadeDescriptorInstallFailure(property, error) {
    if (typeof console === "undefined" || !console || typeof console.warn !== "function") {
      return;
    }
    const cause = error instanceof Error && error.message.trim() !== "" ? error.message : typeof error === "string" && error.trim() !== "" ? error : "unknown error";
    console.warn(
      "[geulbat] runtime storage facade descriptor install failed; using assignment fallback",
      {
        property,
        cause
      }
    );
  }
  function installArtifactRuntimePersistenceFacades(window2, bridge, storageFacadeStore, bootstrapLifecycle) {
    const clearRecord = (record) => {
      for (const key of Object.keys(record)) {
        delete record[key];
      }
    };
    const markDeferredPersistenceFailure = (error) => {
      bootstrapLifecycle.markStorageUnavailable(error);
    };
    const localStorageApi = createLocalStorageFacade({
      bridge,
      store: storageFacadeStore,
      clearRecord,
      markDeferredPersistenceFailure
    });
    const sessionStorageApi = createSessionStorageFacade({
      store: storageFacadeStore,
      clearRecord
    });
    const logicalDatabaseApi = createLogicalDatabaseFacade({
      window: window2,
      bridge,
      store: storageFacadeStore,
      clearRecord
    });
    const storageApi = createStorageFacade({
      window: window2,
      bridge,
      store: storageFacadeStore
    });
    window2.geulbatPersistence = Object.freeze({
      ...bridge.persistenceApi,
      load() {
        return bridge.persistenceApi.loadState();
      },
      save(state, expectedRevision) {
        return bridge.persistenceApi.saveState(state, expectedRevision);
      },
      clear(expectedRevision) {
        return bridge.persistenceApi.clearState(expectedRevision);
      }
    });
    window2.storage = storageApi;
    window2.__GEULBAT_RUNTIME_STORAGE_READY__ = bootstrapLifecycle.loadCurrentAuthorityState(bridge.rawPersistenceApi).then(
      (current) => {
        bootstrapLifecycle.replaceCurrentAuthorityState(current);
      }
    ).catch((error) => {
      bootstrapLifecycle.markStorageUnavailable(error);
    }).then(() => {
      bootstrapLifecycle.setStorageBootstrapReady(true);
      installPersistenceFacadeProperty(
        window2,
        "localStorage",
        localStorageApi,
        (error) => {
          bootstrapLifecycle.markStorageUnavailable(error);
        }
      );
      installPersistenceFacadeProperty(
        window2,
        "sessionStorage",
        sessionStorageApi,
        (error) => {
          bootstrapLifecycle.markStorageUnavailable(error);
        }
      );
      installPersistenceFacadeProperty(
        window2,
        "geulbatDB",
        logicalDatabaseApi,
        (error) => {
          bootstrapLifecycle.markStorageUnavailable(error);
        }
      );
    });
  }
  function installArtifactRuntimePersistenceBootstrap(window2, verbs) {
    const services = createArtifactRuntimePersistenceStore();
    const bridge = createArtifactRuntimePersistenceBridge(
      window2,
      verbs,
      services.bridgeStore
    );
    installArtifactRuntimePersistenceFacades(
      window2,
      bridge,
      services.storageFacadeStore,
      services.bootstrapLifecycle
    );
  }

  // src/features/assistant/runtime-persistence/artifact-runtime-persistence-bootstrap-entry.ts
  function parseInjectedBootstrapValue(serializedValue, field, guard) {
    const parsed = tryParseJsonWithGuard(serializedValue, guard);
    if (!parsed.ok) {
      throw new TypeError(
        \`runtime persistence bootstrap \${field} must be valid JSON with the expected type\`
      );
    }
    return parsed.value;
  }
  function isPersistenceBridgeVersion(value) {
    return isString(value) || isNumber(value);
  }
  function configureRuntimePersistenceWindow(runtimeWindow2) {
    runtimeWindow2.__GEULBAT_PERSISTENCE_BRIDGE_VERSION__ = parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_BRIDGE_VERSION_JSON__",
      "bridge version",
      isPersistenceBridgeVersion
    );
    runtimeWindow2.__GEULBAT_PERSISTENCE_SCOPE_HANDLE__ = parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_SCOPE_HANDLE_JSON__",
      "scope handle",
      isString
    );
    runtimeWindow2.__GEULBAT_PERSISTENCE_PARENT_ORIGIN__ = parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_PARENT_ORIGIN_JSON__",
      "parent origin",
      isString
    );
    runtimeWindow2.__GEULBAT_PERSISTENCE_REQUEST_KIND__ = parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_REQUEST_KIND_JSON__",
      "request kind",
      isString
    );
    runtimeWindow2.__GEULBAT_PERSISTENCE_RESPONSE_KIND__ = parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_RESPONSE_KIND_JSON__",
      "response kind",
      isString
    );
    runtimeWindow2.__GEULBAT_PERSISTENCE_REQUEST_TIMEOUT_MS__ = Number(
      "__GEULBAT_PERSISTENCE_REQUEST_TIMEOUT_MS_VALUE__"
    );
  }
  var runtimeWindow = window;
  configureRuntimePersistenceWindow(runtimeWindow);
  installArtifactRuntimePersistenceBootstrap(runtimeWindow, {
    loadVerb: parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_VERB_LOAD_JSON__",
      "load verb",
      isString
    ),
    saveVerb: parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_VERB_SAVE_JSON__",
      "save verb",
      isString
    ),
    clearVerb: parseInjectedBootstrapValue(
      "__GEULBAT_PERSISTENCE_VERB_CLEAR_JSON__",
      "clear verb",
      isString
    )
  });
})();
`;
