import { createHash } from 'node:crypto';
import {
  ImageGenerationError,
  type GeneratedImageAsset,
  type GeneratedImageMimeType,
} from './contract.js';

// 생성 후보 검증(artifact-media 소유): 프로바이더가 무엇을 주장하든
// 실제 바이트로 MIME을 판별하고, 크기 정책과 digest를 커밋 전에 강제한다.

const DEFAULT_MAX_GENERATED_IMAGE_BYTES = 32 * 1024 * 1024;

function resolveMaxGeneratedImageBytes(): number {
  const raw = process.env.GEULBAT_IMAGE_GENERATION_MAX_BYTES;
  if (raw === undefined) {
    return DEFAULT_MAX_GENERATED_IMAGE_BYTES;
  }
  const parsed = Number.parseInt(raw, 10);
  return Number.isFinite(parsed) && parsed > 0
    ? parsed
    : DEFAULT_MAX_GENERATED_IMAGE_BYTES;
}

// 매직 바이트 스니핑 — 프로바이더가 주장하는 MIME이 아니라 실제 바이트로 판별한다.
function sniffGeneratedImageMimeType(
  bytes: Buffer,
): GeneratedImageMimeType | null {
  if (
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47 &&
    bytes[4] === 0x0d &&
    bytes[5] === 0x0a &&
    bytes[6] === 0x1a &&
    bytes[7] === 0x0a
  ) {
    return 'image/png';
  }
  if (
    bytes.length >= 3 &&
    bytes[0] === 0xff &&
    bytes[1] === 0xd8 &&
    bytes[2] === 0xff
  ) {
    return 'image/jpeg';
  }
  if (
    bytes.length >= 12 &&
    bytes.toString('latin1', 0, 4) === 'RIFF' &&
    bytes.toString('latin1', 8, 12) === 'WEBP'
  ) {
    return 'image/webp';
  }
  return null;
}

export function validateGeneratedImageBase64(args: {
  dataBase64: string;
  maxBytes?: number;
}): GeneratedImageAsset {
  const dataBase64 = args.dataBase64.trim();
  if (dataBase64.length === 0) {
    throw new ImageGenerationError({
      surface: 'candidate_validation',
      reasonCode: 'empty_image_data',
      message: 'provider returned empty image data',
    });
  }

  let bytes: Buffer;
  try {
    bytes = Buffer.from(dataBase64, 'base64');
  } catch (error: unknown) {
    throw new ImageGenerationError({
      surface: 'candidate_validation',
      reasonCode: 'invalid_base64',
      message: 'provider returned undecodable image data',
      cause: error,
    });
  }
  if (bytes.length === 0) {
    throw new ImageGenerationError({
      surface: 'candidate_validation',
      reasonCode: 'invalid_base64',
      message: 'provider returned undecodable image data',
    });
  }

  const maxBytes = args.maxBytes ?? resolveMaxGeneratedImageBytes();
  if (bytes.length > maxBytes) {
    throw new ImageGenerationError({
      surface: 'candidate_validation',
      reasonCode: 'image_too_large',
      message: `generated image is ${bytes.length} bytes; policy allows ${maxBytes}`,
    });
  }

  const mimeType = sniffGeneratedImageMimeType(bytes);
  if (mimeType === null) {
    throw new ImageGenerationError({
      surface: 'candidate_validation',
      reasonCode: 'unsupported_image_format',
      message:
        'generated bytes are not a supported image format (png/jpeg/webp)',
    });
  }

  return {
    mimeType,
    byteLength: bytes.length,
    dataBase64: bytes.toString('base64'),
    digest: {
      algorithm: 'sha256',
      encoding: 'hex',
      value: createHash('sha256').update(bytes).digest('hex'),
    },
  };
}
