import type { CSSProperties } from 'react';

// 좌측 rail 대화 목록 — Modern Heritage 토큰만 참조 (색상 리터럴 금지)
export function getThreadButtonStyle(isSelected: boolean): CSSProperties {
  return {
    background: isSelected ? 'var(--surface-container)' : 'none',
    boxShadow: isSelected ? 'inset 2px 0 0 0 var(--primary)' : 'none',
    border: 'none',
    cursor: 'pointer',
    width: '100%',
    textAlign: 'left',
    fontSize: 13,
    padding: '5px 8px',
    borderRadius: 4,
    color: 'var(--on-surface-variant)',
    fontFamily: 'var(--font-ui-label)',
    transition: 'background var(--transition-base)',
  };
}

export const threadListAlertStyle: CSSProperties = {
  marginBottom: 10,
  padding: '8px 10px',
  borderRadius: 8,
  background: 'var(--warning-bg)',
  color: 'var(--warning-text)',
  fontSize: 12,
  lineHeight: 1.45,
};

// 세션 전체 관리 다이얼로그 — 카드 골격은 video-settings-card를 재사용하고
// 여기는 내부 행/컨트롤 토큰만 정의한다
export const sessionManagerStyles = {
  headerSpacer: {
    flex: 1,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: 600,
    color: 'var(--on-surface)',
    margin: 0,
  },
  headerButton: {
    border: '1px solid var(--outline-variant)',
    background: 'var(--surface-container)',
    color: 'var(--on-surface-variant)',
    borderRadius: 999,
    fontSize: 12,
    padding: '5px 12px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    fontFamily: 'var(--font-ui-label)',
  },
  primaryButton: {
    // 폴더 열기와 같은 세이지 — 잉크색(--primary)은 이 화면에서 혼자 튄다
    border: 'none',
    background: 'var(--secondary)',
    color: 'var(--on-primary)',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
    padding: '6px 14px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    fontFamily: 'var(--font-ui-label)',
  },
  iconButton: {
    border: '1px solid var(--outline-variant)',
    background: 'var(--surface-container)',
    color: 'var(--on-surface-variant)',
    borderRadius: 999,
    fontSize: 13,
    lineHeight: 1,
    padding: '7px 9px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    fontFamily: 'var(--font-ui-label)',
  },
  search: {
    width: '100%',
    boxSizing: 'border-box',
    border: '1px solid var(--outline-variant)',
    background: 'var(--surface-container)',
    color: 'var(--on-surface)',
    borderRadius: 10,
    fontSize: 14,
    padding: '11px 16px',
    marginBottom: 8,
    fontFamily: 'var(--font-ui-label)',
  },
  groupLabel: {
    fontSize: 12,
    color: 'var(--on-surface-muted)',
    margin: '16px 0 6px',
    letterSpacing: '0.04em',
  },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    borderRadius: 6,
    padding: '7px 8px',
  },
  rowMain: {
    flex: 1,
    minWidth: 0,
    background: 'none',
    border: 'none',
    textAlign: 'left',
    cursor: 'pointer',
    padding: 0,
    color: 'var(--on-surface)',
    fontFamily: 'var(--font-ui-label)',
  },
  rowTitle: {
    // 전체 보기 제목 줄은 원고 제목과 같은 글밭 세리프로
    fontFamily: 'var(--font-prose-serif)',
    fontSize: 15.5,
    fontWeight: 500,
    color: 'var(--on-surface)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  rowMeta: {
    fontSize: 12.5,
    color: 'var(--on-surface-muted)',
    whiteSpace: 'nowrap',
    flexShrink: 0,
  },
  quietAction: {
    border: 'none',
    background: 'transparent',
    color: 'var(--on-surface-muted)',
    fontSize: 11,
    padding: '3px 6px',
    borderRadius: 4,
    cursor: 'pointer',
    flexShrink: 0,
    fontFamily: 'var(--font-ui-label)',
  },
  dangerAction: {
    border: 'none',
    background: 'transparent',
    color: 'var(--error)',
    fontSize: 11,
    padding: '3px 6px',
    borderRadius: 4,
    cursor: 'pointer',
    flexShrink: 0,
    fontFamily: 'var(--font-ui-label)',
  },
  renameInput: {
    flex: 1,
    minWidth: 0,
    border: '1px solid var(--primary)',
    background: 'var(--surface-container)',
    color: 'var(--on-surface)',
    borderRadius: 6,
    fontSize: 13,
    padding: '5px 8px',
    fontFamily: 'var(--font-ui-label)',
  },
  dangerButton: {
    border: 'none',
    background: 'var(--error)',
    color: 'var(--on-primary)',
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 600,
    padding: '6px 14px',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    fontFamily: 'var(--font-ui-label)',
  },
} satisfies Record<string, CSSProperties>;

export const threadListStyles = {
  section: {
    margin: '0 12px',
  },
  emptyState: {
    fontSize: 12,
    color: 'var(--on-surface-muted)',
  },
  list: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  row: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 8,
  },
  threadTitle: {
    fontWeight: 500,
    color: 'var(--on-surface)',
  },
  threadMeta: {
    fontSize: 11,
    color: 'var(--on-surface-muted)',
  },
  renameInput: {
    flex: 1,
    minWidth: 0,
    border: '1px solid var(--primary)',
    background: 'var(--surface-container)',
    color: 'var(--on-surface)',
    borderRadius: 6,
    fontSize: 13,
    padding: '5px 8px',
    fontFamily: 'var(--font-ui-label)',
  },
  managerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    marginBottom: 6,
  },
  managerLabel: {
    fontSize: 11,
    color: 'var(--on-surface-muted)',
    fontFamily: 'var(--font-ui-label)',
  },
  managerButton: {
    border: 'none',
    background: 'transparent',
    color: 'var(--on-surface-muted)',
    fontSize: 11,
    padding: '3px 6px',
    borderRadius: 4,
    cursor: 'pointer',
    fontFamily: 'var(--font-ui-label)',
  },
} satisfies Record<string, CSSProperties>;
